-- MySQL Script generated by MySQL Workbench
-- Thu Feb 29 22:22:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_dogsitters
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_dogsitters
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_dogsitters` DEFAULT CHARACTER SET utf8 ;
USE `db_dogsitters` ;

-- -----------------------------------------------------
-- Table `db_dogsitters`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dogsitters`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  `date_birth` DATE NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `image` MEDIUMBLOB NULL,
  `phone` VARCHAR(50) NOT NULL,
  `dogsitter` INT NOT NULL,
  `about` VARCHAR(10000) NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dogsitters`.`dogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dogsitters`.`dogs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `name` VARCHAR(300) NOT NULL,
  `date_birth` DATE NOT NULL,
  `breed` VARCHAR(100) NOT NULL,
  `about` VARCHAR(10000) NOT NULL,
  `image` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`, `id_user`),
  INDEX `fk_dogs_users_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_dogs_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_dogsitters`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dogsitters`.`medical_dogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dogsitters`.`medical_dogs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_dog` INT NOT NULL,
  `id_user` INT NOT NULL,
  `date` DATE NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`, `id_dog`, `id_user`),
  INDEX `fk_medical_dogs_dogs1_idx` (`id_dog` ASC, `id_user` ASC) VISIBLE,
  CONSTRAINT `fk_medical_dogs_dogs1`
    FOREIGN KEY (`id_dog` , `id_user`)
    REFERENCES `db_dogsitters`.`dogs` (`id` , `id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dogsitters`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dogsitters`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `date` DATE NOT NULL,
  `description` VARCHAR(10000) NOT NULL,
  PRIMARY KEY (`id`, `id_user`),
  INDEX `fk_articles_users1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_articles_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_dogsitters`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
